//由Translator++生成。
// 不要直接编辑此文件。
var $plugins =
[
  {
    "name": "YEP_CoreEngine",
    "status": true,
    "description": "v1.32 解像度、所持金、アイテム、レベル、能力値の上限など様々な変更が可能になります",
    "parameters": {
      "---画面---": "",
      "Screen Width": "1024",
      "Screen Height": "576",
      "Scale Battlebacks": "false",
      "Scale Title": "false",
      "Scale Game Over": "false",
      "Open Console": "false",
      "Reposition Battlers": "false",
      "GameFont Load Timer": "0",
      "Update Real Scale": "false",
      "Collection Clear": "false",
      "---所持金---": "",
      "Gold Max": "999999",
      "Gold Font Size": "22",
      "Gold Icon": "313",
      "Gold Overlap": "999999+",
      "---アイテム---": "",
      "Default Max": "99",
      "Quantity Text Size": "20",
      "---能力値---": "",
      "Max Level": "99",
      "Actor MaxHP": "9999999999",
      "Actor MaxMP": "9999",
      "Actor Parameter": "999",
      "Enemy MaxHP": "9999999999",
      "Enemy MaxMP": "9999",
      "Enemy Parameter": "999",
      "---戦闘---": "",
      "Animation Rate": "4",
      "Flash Target": "true",
      "Show Events Transition": "true",
      "Show Events Snapshot": "false",
      "---マップ最適化---": "",
      "Refresh Update HP": "true",
      "Refresh Update MP": "true",
      "Refresh Update TP": "false",
      "---フォント---": "",
      "Chinese Font": "SimHei, Heiti TC, sans-serif",
      "Korean Font": "Dotum, AppleGothic, sans-serif",
      "Default Font": "GameFont, Verdana, Arial, Courier New",
      "Font Size": "24",
      "Text Align": "left",
      "---ウィンドウ---": "",
      "Digit Grouping": "true",
      "Line Height": "36",
      "Icon Width": "32",
      "Icon Height": "32",
      "Face Width": "144",
      "Face Height": "144",
      "Window Padding": "18",
      "Text Padding": "6",
      "Window Opacity": "192",
      "Gauge Outline": "false",
      "Gauge Height": "18",
      "Menu TP Bar": "true",
      "---ウィンドウ色---": "",
      "Color: Normal": "0",
      "Color: System": "16",
      "Color: Crisis": "17",
      "Color: Death": "18",
      "Color: Gauge Back": "19",
      "Color: HP Gauge 1": "20",
      "Color: HP Gauge 2": "21",
      "Color: MP Gauge 1": "22",
      "Color: MP Gauge 2": "23",
      "Color: MP Cost": "23",
      "Color: Power Up": "24",
      "Color: Power Down": "25",
      "Color: TP Gauge 1": "28",
      "Color: TP Gauge 2": "29",
      "Color: TP Cost Color": "29"
    }
  },
  {
    "name": "YEP_MainMenuManager",
    "status": true,
    "description": "v1.03 メインメニューに様々な変更を加えます。",
    "parameters": {
      "---General---": "",
      "Hide Actor Window": "false",
      "Hide Gold Window": "true",
      "Blurry Background": "true",
      "---Command---": "",
      "Command Alignment": "left",
      "Command Position": "left",
      "Command Columns": "1",
      "Command Rows": "Math.min(10, Math.ceil(this.maxItems() / this.maxCols()))",
      "Command Width": "240",
      "---Menu Items---": "",
      "---Menu 1---": "",
      "Menu 1 Name": "",
      "Menu 1 Symbol": "",
      "Menu 1 Show": "",
      "Menu 1 Enabled": "",
      "Menu 1 Ext": "",
      "Menu 1 Main Bind": "",
      "Menu 1 Actor Bind": "",
      "---Menu 2---": "",
      "Menu 2 Name": "",
      "Menu 2 Symbol": "",
      "Menu 2 Show": "",
      "Menu 2 Enabled": "",
      "Menu 2 Ext": "",
      "Menu 2 Main Bind": "",
      "Menu 2 Actor Bind": "",
      "---Menu 3---": "",
      "Menu 3 Name": "",
      "Menu 3 Symbol": "",
      "Menu 3 Show": "",
      "Menu 3 Enabled": "",
      "Menu 3 Ext": "",
      "Menu 3 Main Bind": "",
      "Menu 3 Actor Bind": "",
      "---Menu 4---": "",
      "Menu 4 Name": "",
      "Menu 4 Symbol": "",
      "Menu 4 Show": "",
      "Menu 4 Enabled": "",
      "Menu 4 Ext": "",
      "Menu 4 Main Bind": "",
      "Menu 4 Actor Bind": "",
      "---Menu 5---": "",
      "Menu 5 Name": "",
      "Menu 5 Symbol": "",
      "Menu 5 Show": "",
      "Menu 5 Enabled": "",
      "Menu 5 Ext": "",
      "Menu 5 Main Bind": "",
      "Menu 5 Actor Bind": "",
      "---Menu 6---": "",
      "Menu 6 Name": "",
      "Menu 6 Symbol": "",
      "Menu 6 Show": "",
      "Menu 6 Enabled": "",
      "Menu 6 Ext": "",
      "Menu 6 Main Bind": "",
      "Menu 6 Actor Bind": "",
      "---Menu 7---": "",
      "Menu 7 Name": "",
      "Menu 7 Symbol": "",
      "Menu 7 Show": "",
      "Menu 7 Enabled": "",
      "Menu 7 Ext": "",
      "Menu 7 Main Bind": "",
      "Menu 7 Actor Bind": "",
      "---Menu 8---": "",
      "Menu 8 Name": "",
      "Menu 8 Symbol": "",
      "Menu 8 Show": "",
      "Menu 8 Enabled": "",
      "Menu 8 Ext": "",
      "Menu 8 Main Bind": "",
      "Menu 8 Actor Bind": "",
      "---Menu 9---": "",
      "Menu 9 Name": "",
      "Menu 9 Symbol": "",
      "Menu 9 Show": "",
      "Menu 9 Enabled": "",
      "Menu 9 Ext": "",
      "Menu 9 Main Bind": "",
      "Menu 9 Actor Bind": "",
      "---Menu 10---": "",
      "Menu 10 Name": "TextManager.item",
      "Menu 10 Symbol": "item",
      "Menu 10 Show": "this.needsCommand('item')",
      "Menu 10 Enabled": "this.areMainCommandsEnabled()",
      "Menu 10 Ext": "",
      "Menu 10 Main Bind": "this.commandItem.bind(this)",
      "Menu 10 Actor Bind": "",
      "---Menu 11---": "",
      "Menu 11 Name": "",
      "Menu 11 Symbol": "",
      "Menu 11 Show": "",
      "Menu 11 Enabled": "",
      "Menu 11 Ext": "",
      "Menu 11 Main Bind": "",
      "Menu 11 Actor Bind": "",
      "---Menu 12---": "",
      "Menu 12 Name": "",
      "Menu 12 Symbol": "",
      "Menu 12 Show": "",
      "Menu 12 Enabled": "",
      "Menu 12 Ext": "",
      "Menu 12 Main Bind": "",
      "Menu 12 Actor Bind": "",
      "---Menu 13---": "",
      "Menu 13 Name": "",
      "Menu 13 Symbol": "",
      "Menu 13 Show": "",
      "Menu 13 Enabled": "",
      "Menu 13 Ext": "",
      "Menu 13 Main Bind": "",
      "Menu 13 Actor Bind": "",
      "---Menu 14---": "",
      "Menu 14 Name": "",
      "Menu 14 Symbol": "",
      "Menu 14 Show": "",
      "Menu 14 Enabled": "",
      "Menu 14 Ext": "",
      "Menu 14 Main Bind": "",
      "Menu 14 Actor Bind": "",
      "---Menu 15---": "",
      "Menu 15 Name": "TextManager.skill",
      "Menu 15 Symbol": "skill",
      "Menu 15 Show": "this.needsCommand('skill')",
      "Menu 15 Enabled": "this.areMainCommandsEnabled()",
      "Menu 15 Ext": "",
      "Menu 15 Main Bind": "this.commandPersonal.bind(this)",
      "Menu 15 Actor Bind": "SceneManager.push(Scene_Skill)",
      "---Menu 16---": "",
      "Menu 16 Name": "",
      "Menu 16 Symbol": "",
      "Menu 16 Show": "",
      "Menu 16 Enabled": "",
      "Menu 16 Ext": "",
      "Menu 16 Main Bind": "",
      "Menu 16 Actor Bind": "",
      "---Menu 17---": "",
      "Menu 17 Name": "",
      "Menu 17 Symbol": "",
      "Menu 17 Show": "",
      "Menu 17 Enabled": "",
      "Menu 17 Ext": "",
      "Menu 17 Main Bind": "",
      "Menu 17 Actor Bind": "",
      "---Menu 18---": "",
      "Menu 18 Name": "",
      "Menu 18 Symbol": "",
      "Menu 18 Show": "",
      "Menu 18 Enabled": "",
      "Menu 18 Ext": "",
      "Menu 18 Main Bind": "",
      "Menu 18 Actor Bind": "",
      "---Menu 19---": "",
      "Menu 19 Name": "",
      "Menu 19 Symbol": "",
      "Menu 19 Show": "",
      "Menu 19 Enabled": "",
      "Menu 19 Ext": "",
      "Menu 19 Main Bind": "",
      "Menu 19 Actor Bind": "",
      "---Menu 20---": "",
      "Menu 20 Name": "TextManager.equip",
      "Menu 20 Symbol": "equip",
      "Menu 20 Show": "false",
      "Menu 20 Enabled": "true",
      "Menu 20 Ext": "13",
      "Menu 20 Main Bind": "this.callCommonEvent.bind(this)",
      "Menu 20 Actor Bind": "",
      "---Menu 21---": "",
      "Menu 21 Name": "",
      "Menu 21 Symbol": "",
      "Menu 21 Show": "",
      "Menu 21 Enabled": "",
      "Menu 21 Ext": "",
      "Menu 21 Main Bind": "",
      "Menu 21 Actor Bind": "",
      "---Menu 22---": "",
      "Menu 22 Name": "",
      "Menu 22 Symbol": "",
      "Menu 22 Show": "",
      "Menu 22 Enabled": "",
      "Menu 22 Ext": "",
      "Menu 22 Main Bind": "",
      "Menu 22 Actor Bind": "",
      "---Menu 23---": "",
      "Menu 23 Name": "",
      "Menu 23 Symbol": "",
      "Menu 23 Show": "",
      "Menu 23 Enabled": "",
      "Menu 23 Ext": "",
      "Menu 23 Main Bind": "",
      "Menu 23 Actor Bind": "",
      "---Menu 24---": "",
      "Menu 24 Name": "",
      "Menu 24 Symbol": "",
      "Menu 24 Show": "",
      "Menu 24 Enabled": "",
      "Menu 24 Ext": "",
      "Menu 24 Main Bind": "",
      "Menu 24 Actor Bind": "",
      "---Menu 25---": "",
      "Menu 25 Name": "Yanfly.Param.CCCCmdName",
      "Menu 25 Symbol": "class",
      "Menu 25 Show": "false",
      "Menu 25 Enabled": "$gameSystem.isEnableClass() && this.areMainCommandsEnabled()",
      "Menu 25 Ext": "",
      "Menu 25 Main Bind": "this.commandPersonal.bind(this)",
      "Menu 25 Actor Bind": "SceneManager.push(Scene_Class)",
      "---Menu 26---": "",
      "Menu 26 Name": "",
      "Menu 26 Symbol": "",
      "Menu 26 Show": "",
      "Menu 26 Enabled": "",
      "Menu 26 Ext": "",
      "Menu 26 Main Bind": "",
      "Menu 26 Actor Bind": "",
      "---Menu 27---": "",
      "Menu 27 Name": "",
      "Menu 27 Symbol": "",
      "Menu 27 Show": "",
      "Menu 27 Enabled": "",
      "Menu 27 Ext": "",
      "Menu 27 Main Bind": "",
      "Menu 27 Actor Bind": "",
      "---Menu 28---": "",
      "Menu 28 Name": "",
      "Menu 28 Symbol": "",
      "Menu 28 Show": "",
      "Menu 28 Enabled": "",
      "Menu 28 Ext": "",
      "Menu 28 Main Bind": "",
      "Menu 28 Actor Bind": "",
      "---Menu 29---": "",
      "Menu 29 Name": "",
      "Menu 29 Symbol": "",
      "Menu 29 Show": "",
      "Menu 29 Enabled": "",
      "Menu 29 Ext": "",
      "Menu 29 Main Bind": "",
      "Menu 29 Actor Bind": "",
      "---Menu 30---": "",
      "Menu 30 Name": "",
      "Menu 30 Symbol": "",
      "Menu 30 Show": "",
      "Menu 30 Enabled": "",
      "Menu 30 Ext": "",
      "Menu 30 Main Bind": "",
      "Menu 30 Actor Bind": "",
      "---Menu 31---": "",
      "Menu 31 Name": "",
      "Menu 31 Symbol": "",
      "Menu 31 Show": "",
      "Menu 31 Enabled": "",
      "Menu 31 Ext": "",
      "Menu 31 Main Bind": "",
      "Menu 31 Actor Bind": "",
      "---Menu 32---": "",
      "Menu 32 Name": "",
      "Menu 32 Symbol": "",
      "Menu 32 Show": "",
      "Menu 32 Enabled": "",
      "Menu 32 Ext": "",
      "Menu 32 Main Bind": "",
      "Menu 32 Actor Bind": "",
      "---Menu 33---": "",
      "Menu 33 Name": "",
      "Menu 33 Symbol": "",
      "Menu 33 Show": "",
      "Menu 33 Enabled": "",
      "Menu 33 Ext": "",
      "Menu 33 Main Bind": "",
      "Menu 33 Actor Bind": "",
      "---Menu 34---": "",
      "Menu 34 Name": "",
      "Menu 34 Symbol": "",
      "Menu 34 Show": "",
      "Menu 34 Enabled": "",
      "Menu 34 Ext": "",
      "Menu 34 Main Bind": "",
      "Menu 34 Actor Bind": "",
      "---Menu 35---": "",
      "Menu 35 Name": "",
      "Menu 35 Symbol": "",
      "Menu 35 Show": "",
      "Menu 35 Enabled": "",
      "Menu 35 Ext": "",
      "Menu 35 Main Bind": "",
      "Menu 35 Actor Bind": "",
      "---Menu 36---": "",
      "Menu 36 Name": "",
      "Menu 36 Symbol": "",
      "Menu 36 Show": "",
      "Menu 36 Enabled": "",
      "Menu 36 Ext": "",
      "Menu 36 Main Bind": "",
      "Menu 36 Actor Bind": "",
      "---Menu 37---": "",
      "Menu 37 Name": "",
      "Menu 37 Symbol": "",
      "Menu 37 Show": "",
      "Menu 37 Enabled": "",
      "Menu 37 Ext": "",
      "Menu 37 Main Bind": "",
      "Menu 37 Actor Bind": "",
      "---Menu 38---": "",
      "Menu 38 Name": "",
      "Menu 38 Symbol": "",
      "Menu 38 Show": "",
      "Menu 38 Enabled": "",
      "Menu 38 Ext": "",
      "Menu 38 Main Bind": "",
      "Menu 38 Actor Bind": "",
      "---Menu 39---": "",
      "Menu 39 Name": "",
      "Menu 39 Symbol": "",
      "Menu 39 Show": "",
      "Menu 39 Enabled": "",
      "Menu 39 Ext": "",
      "Menu 39 Main Bind": "",
      "Menu 39 Actor Bind": "",
      "---Menu 40---": "",
      "Menu 40 Name": "",
      "Menu 40 Symbol": "",
      "Menu 40 Show": "",
      "Menu 40 Enabled": "",
      "Menu 40 Ext": "",
      "Menu 40 Main Bind": "",
      "Menu 40 Actor Bind": "",
      "---Menu 41---": "",
      "Menu 41 Name": "",
      "Menu 41 Symbol": "",
      "Menu 41 Show": "",
      "Menu 41 Enabled": "",
      "Menu 41 Ext": "",
      "Menu 41 Main Bind": "",
      "Menu 41 Actor Bind": "",
      "---Menu 42---": "",
      "Menu 42 Name": "",
      "Menu 42 Symbol": "",
      "Menu 42 Show": "",
      "Menu 42 Enabled": "",
      "Menu 42 Ext": "",
      "Menu 42 Main Bind": "",
      "Menu 42 Actor Bind": "",
      "---Menu 43---": "",
      "Menu 43 Name": "",
      "Menu 43 Symbol": "",
      "Menu 43 Show": "",
      "Menu 43 Enabled": "",
      "Menu 43 Ext": "",
      "Menu 43 Main Bind": "",
      "Menu 43 Actor Bind": "",
      "---Menu 44---": "",
      "Menu 44 Name": "",
      "Menu 44 Symbol": "",
      "Menu 44 Show": "",
      "Menu 44 Enabled": "",
      "Menu 44 Ext": "",
      "Menu 44 Main Bind": "",
      "Menu 44 Actor Bind": "",
      "---Menu 45---": "",
      "Menu 45 Name": "",
      "Menu 45 Symbol": "",
      "Menu 45 Show": "",
      "Menu 45 Enabled": "",
      "Menu 45 Ext": "",
      "Menu 45 Main Bind": "",
      "Menu 45 Actor Bind": "",
      "---Menu 46---": "",
      "Menu 46 Name": "",
      "Menu 46 Symbol": "",
      "Menu 46 Show": "",
      "Menu 46 Enabled": "",
      "Menu 46 Ext": "",
      "Menu 46 Main Bind": "",
      "Menu 46 Actor Bind": "",
      "---Menu 47---": "",
      "Menu 47 Name": "",
      "Menu 47 Symbol": "",
      "Menu 47 Show": "",
      "Menu 47 Enabled": "",
      "Menu 47 Ext": "",
      "Menu 47 Main Bind": "",
      "Menu 47 Actor Bind": "",
      "---Menu 48---": "",
      "Menu 48 Name": "",
      "Menu 48 Symbol": "",
      "Menu 48 Show": "",
      "Menu 48 Enabled": "",
      "Menu 48 Ext": "",
      "Menu 48 Main Bind": "",
      "Menu 48 Actor Bind": "",
      "---Menu 49---": "",
      "Menu 49 Name": "",
      "Menu 49 Symbol": "",
      "Menu 49 Show": "",
      "Menu 49 Enabled": "",
      "Menu 49 Ext": "",
      "Menu 49 Main Bind": "",
      "Menu 49 Actor Bind": "",
      "---Menu 50---": "",
      "Menu 50 Name": "TextManager.status",
      "Menu 50 Symbol": "status",
      "Menu 50 Show": "this.needsCommand('status')",
      "Menu 50 Enabled": "this.areMainCommandsEnabled()",
      "Menu 50 Ext": "",
      "Menu 50 Main Bind": "this.commandPersonal.bind(this)",
      "Menu 50 Actor Bind": "SceneManager.push(Scene_Status)",
      "---Menu 51---": "",
      "Menu 51 Name": "",
      "Menu 51 Symbol": "",
      "Menu 51 Show": "",
      "Menu 51 Enabled": "",
      "Menu 51 Ext": "",
      "Menu 51 Main Bind": "",
      "Menu 51 Actor Bind": "",
      "---Menu 52---": "",
      "Menu 52 Name": "",
      "Menu 52 Symbol": "",
      "Menu 52 Show": "",
      "Menu 52 Enabled": "",
      "Menu 52 Ext": "",
      "Menu 52 Main Bind": "",
      "Menu 52 Actor Bind": "",
      "---Menu 53---": "",
      "Menu 53 Name": "",
      "Menu 53 Symbol": "",
      "Menu 53 Show": "",
      "Menu 53 Enabled": "",
      "Menu 53 Ext": "",
      "Menu 53 Main Bind": "",
      "Menu 53 Actor Bind": "",
      "---Menu 54---": "",
      "Menu 54 Name": "",
      "Menu 54 Symbol": "",
      "Menu 54 Show": "",
      "Menu 54 Enabled": "",
      "Menu 54 Ext": "",
      "Menu 54 Main Bind": "",
      "Menu 54 Actor Bind": "",
      "---Menu 55---": "",
      "Menu 55 Name": "TextManager.formation",
      "Menu 55 Symbol": "formation",
      "Menu 55 Show": "false",
      "Menu 55 Enabled": "true",
      "Menu 55 Ext": "12",
      "Menu 55 Main Bind": "this.callCommonEvent.bind(this)",
      "Menu 55 Actor Bind": "",
      "---Menu 56---": "",
      "Menu 56 Name": "",
      "Menu 56 Symbol": "",
      "Menu 56 Show": "",
      "Menu 56 Enabled": "",
      "Menu 56 Ext": "",
      "Menu 56 Main Bind": "",
      "Menu 56 Actor Bind": "",
      "---Menu 57---": "",
      "Menu 57 Name": "",
      "Menu 57 Symbol": "",
      "Menu 57 Show": "",
      "Menu 57 Enabled": "",
      "Menu 57 Ext": "",
      "Menu 57 Main Bind": "",
      "Menu 57 Actor Bind": "",
      "---Menu 58---": "",
      "Menu 58 Name": "",
      "Menu 58 Symbol": "",
      "Menu 58 Show": "",
      "Menu 58 Enabled": "",
      "Menu 58 Ext": "",
      "Menu 58 Main Bind": "",
      "Menu 58 Actor Bind": "",
      "---Menu 59---": "",
      "Menu 59 Name": "",
      "Menu 59 Symbol": "",
      "Menu 59 Show": "",
      "Menu 59 Enabled": "",
      "Menu 59 Ext": "",
      "Menu 59 Main Bind": "",
      "Menu 59 Actor Bind": "",
      "---Menu 60---": "",
      "Menu 60 Name": "",
      "Menu 60 Symbol": "",
      "Menu 60 Show": "",
      "Menu 60 Enabled": "",
      "Menu 60 Ext": "",
      "Menu 60 Main Bind": "",
      "Menu 60 Actor Bind": "",
      "---Menu 61---": "",
      "Menu 61 Name": "",
      "Menu 61 Symbol": "",
      "Menu 61 Show": "",
      "Menu 61 Enabled": "",
      "Menu 61 Ext": "",
      "Menu 61 Main Bind": "",
      "Menu 61 Actor Bind": "",
      "---Menu 62---": "",
      "Menu 62 Name": "",
      "Menu 62 Symbol": "",
      "Menu 62 Show": "",
      "Menu 62 Enabled": "",
      "Menu 62 Ext": "",
      "Menu 62 Main Bind": "",
      "Menu 62 Actor Bind": "",
      "---Menu 63---": "",
      "Menu 63 Name": "",
      "Menu 63 Symbol": "",
      "Menu 63 Show": "",
      "Menu 63 Enabled": "",
      "Menu 63 Ext": "",
      "Menu 63 Main Bind": "",
      "Menu 63 Actor Bind": "",
      "---Menu 64---": "",
      "Menu 64 Name": "",
      "Menu 64 Symbol": "",
      "Menu 64 Show": "",
      "Menu 64 Enabled": "",
      "Menu 64 Ext": "",
      "Menu 64 Main Bind": "",
      "Menu 64 Actor Bind": "",
      "---Menu 65---": "",
      "Menu 65 Name": "",
      "Menu 65 Symbol": "",
      "Menu 65 Show": "",
      "Menu 65 Enabled": "",
      "Menu 65 Ext": "",
      "Menu 65 Main Bind": "",
      "Menu 65 Actor Bind": "",
      "---Menu 66---": "",
      "Menu 66 Name": "",
      "Menu 66 Symbol": "",
      "Menu 66 Show": "",
      "Menu 66 Enabled": "",
      "Menu 66 Ext": "",
      "Menu 66 Main Bind": "",
      "Menu 66 Actor Bind": "",
      "---Menu 67---": "",
      "Menu 67 Name": "",
      "Menu 67 Symbol": "",
      "Menu 67 Show": "",
      "Menu 67 Enabled": "",
      "Menu 67 Ext": "",
      "Menu 67 Main Bind": "",
      "Menu 67 Actor Bind": "",
      "---Menu 68---": "",
      "Menu 68 Name": "",
      "Menu 68 Symbol": "",
      "Menu 68 Show": "",
      "Menu 68 Enabled": "",
      "Menu 68 Ext": "",
      "Menu 68 Main Bind": "",
      "Menu 68 Actor Bind": "",
      "---Menu 69---": "",
      "Menu 69 Name": "",
      "Menu 69 Symbol": "",
      "Menu 69 Show": "",
      "Menu 69 Enabled": "",
      "Menu 69 Ext": "",
      "Menu 69 Main Bind": "",
      "Menu 69 Actor Bind": "",
      "---Menu 70---": "",
      "Menu 70 Name": "",
      "Menu 70 Symbol": "",
      "Menu 70 Show": "",
      "Menu 70 Enabled": "",
      "Menu 70 Ext": "",
      "Menu 70 Main Bind": "",
      "Menu 70 Actor Bind": "",
      "---Menu 71---": "",
      "Menu 71 Name": "",
      "Menu 71 Symbol": "",
      "Menu 71 Show": "",
      "Menu 71 Enabled": "",
      "Menu 71 Ext": "",
      "Menu 71 Main Bind": "",
      "Menu 71 Actor Bind": "",
      "---Menu 72---": "",
      "Menu 72 Name": "",
      "Menu 72 Symbol": "",
      "Menu 72 Show": "",
      "Menu 72 Enabled": "",
      "Menu 72 Ext": "",
      "Menu 72 Main Bind": "",
      "Menu 72 Actor Bind": "",
      "---Menu 73---": "",
      "Menu 73 Name": "",
      "Menu 73 Symbol": "",
      "Menu 73 Show": "",
      "Menu 73 Enabled": "",
      "Menu 73 Ext": "",
      "Menu 73 Main Bind": "",
      "Menu 73 Actor Bind": "",
      "---Menu 74---": "",
      "Menu 74 Name": "",
      "Menu 74 Symbol": "",
      "Menu 74 Show": "",
      "Menu 74 Enabled": "",
      "Menu 74 Ext": "",
      "Menu 74 Main Bind": "",
      "Menu 74 Actor Bind": "",
      "---Menu 75---": "",
      "Menu 75 Name": "",
      "Menu 75 Symbol": "",
      "Menu 75 Show": "",
      "Menu 75 Enabled": "",
      "Menu 75 Ext": "",
      "Menu 75 Main Bind": "",
      "Menu 75 Actor Bind": "",
      "---Menu 76---": "",
      "Menu 76 Name": "",
      "Menu 76 Symbol": "",
      "Menu 76 Show": "",
      "Menu 76 Enabled": "",
      "Menu 76 Ext": "",
      "Menu 76 Main Bind": "",
      "Menu 76 Actor Bind": "",
      "---Menu 77---": "",
      "Menu 77 Name": "",
      "Menu 77 Symbol": "",
      "Menu 77 Show": "",
      "Menu 77 Enabled": "",
      "Menu 77 Ext": "",
      "Menu 77 Main Bind": "",
      "Menu 77 Actor Bind": "",
      "---Menu 78---": "",
      "Menu 78 Name": "",
      "Menu 78 Symbol": "",
      "Menu 78 Show": "",
      "Menu 78 Enabled": "",
      "Menu 78 Ext": "",
      "Menu 78 Main Bind": "",
      "Menu 78 Actor Bind": "",
      "---Menu 79---": "",
      "Menu 79 Name": "",
      "Menu 79 Symbol": "",
      "Menu 79 Show": "",
      "Menu 79 Enabled": "",
      "Menu 79 Ext": "",
      "Menu 79 Main Bind": "",
      "Menu 79 Actor Bind": "",
      "---Menu 80---": "",
      "Menu 80 Name": "",
      "Menu 80 Symbol": "",
      "Menu 80 Show": "",
      "Menu 80 Enabled": "",
      "Menu 80 Ext": "",
      "Menu 80 Main Bind": "",
      "Menu 80 Actor Bind": "",
      "---Menu 81---": "",
      "Menu 81 Name": "'Common Event 1'",
      "Menu 81 Symbol": "common event",
      "Menu 81 Show": "false",
      "Menu 81 Enabled": "",
      "Menu 81 Ext": "1",
      "Menu 81 Main Bind": "this.callCommonEvent.bind(this)",
      "Menu 81 Actor Bind": "",
      "---Menu 82---": "",
      "Menu 82 Name": "'Common Event 2'",
      "Menu 82 Symbol": "common event",
      "Menu 82 Show": "false",
      "Menu 82 Enabled": "",
      "Menu 82 Ext": "2",
      "Menu 82 Main Bind": "this.callCommonEvent.bind(this)",
      "Menu 82 Actor Bind": "",
      "---Menu 83---": "",
      "Menu 83 Name": "'Common Event 3'",
      "Menu 83 Symbol": "common event",
      "Menu 83 Show": "false",
      "Menu 83 Enabled": "",
      "Menu 83 Ext": "3",
      "Menu 83 Main Bind": "this.callCommonEvent.bind(this)",
      "Menu 83 Actor Bind": "",
      "---Menu 84---": "",
      "Menu 84 Name": "",
      "Menu 84 Symbol": "",
      "Menu 84 Show": "",
      "Menu 84 Enabled": "",
      "Menu 84 Ext": "",
      "Menu 84 Main Bind": "",
      "Menu 84 Actor Bind": "",
      "---Menu 85---": "",
      "Menu 85 Name": "",
      "Menu 85 Symbol": "",
      "Menu 85 Show": "",
      "Menu 85 Enabled": "",
      "Menu 85 Ext": "",
      "Menu 85 Main Bind": "",
      "Menu 85 Actor Bind": "",
      "---Menu 86---": "",
      "Menu 86 Name": "",
      "Menu 86 Symbol": "",
      "Menu 86 Show": "",
      "Menu 86 Enabled": "",
      "Menu 86 Ext": "",
      "Menu 86 Main Bind": "",
      "Menu 86 Actor Bind": "",
      "---Menu 87---": "",
      "Menu 87 Name": "",
      "Menu 87 Symbol": "",
      "Menu 87 Show": "",
      "Menu 87 Enabled": "",
      "Menu 87 Ext": "",
      "Menu 87 Main Bind": "",
      "Menu 87 Actor Bind": "",
      "---Menu 88---": "",
      "Menu 88 Name": "",
      "Menu 88 Symbol": "",
      "Menu 88 Show": "",
      "Menu 88 Enabled": "",
      "Menu 88 Ext": "",
      "Menu 88 Main Bind": "",
      "Menu 88 Actor Bind": "",
      "---Menu 89---": "",
      "Menu 89 Name": "",
      "Menu 89 Symbol": "",
      "Menu 89 Show": "",
      "Menu 89 Enabled": "",
      "Menu 89 Ext": "",
      "Menu 89 Main Bind": "",
      "Menu 89 Actor Bind": "",
      "---Menu 90---": "",
      "Menu 90 Name": "TextManager.options",
      "Menu 90 Symbol": "options",
      "Menu 90 Show": "true",
      "Menu 90 Enabled": "",
      "Menu 90 Ext": "",
      "Menu 90 Main Bind": "this.commandOptions.bind(this)",
      "Menu 90 Actor Bind": "",
      "---Menu 91---": "",
      "Menu 91 Name": "",
      "Menu 91 Symbol": "",
      "Menu 91 Show": "",
      "Menu 91 Enabled": "",
      "Menu 91 Ext": "",
      "Menu 91 Main Bind": "",
      "Menu 91 Actor Bind": "",
      "---Menu 92---": "",
      "Menu 92 Name": "",
      "Menu 92 Symbol": "",
      "Menu 92 Show": "",
      "Menu 92 Enabled": "",
      "Menu 92 Ext": "",
      "Menu 92 Main Bind": "",
      "Menu 92 Actor Bind": "",
      "---Menu 93---": "",
      "Menu 93 Name": "",
      "Menu 93 Symbol": "",
      "Menu 93 Show": "",
      "Menu 93 Enabled": "",
      "Menu 93 Ext": "",
      "Menu 93 Main Bind": "",
      "Menu 93 Actor Bind": "",
      "---Menu 94---": "",
      "Menu 94 Name": "",
      "Menu 94 Symbol": "",
      "Menu 94 Show": "",
      "Menu 94 Enabled": "",
      "Menu 94 Ext": "",
      "Menu 94 Main Bind": "",
      "Menu 94 Actor Bind": "",
      "---Menu 95---": "",
      "Menu 95 Name": "TextManager.save",
      "Menu 95 Symbol": "save",
      "Menu 95 Show": "this.needsCommand('save')",
      "Menu 95 Enabled": "this.isSaveEnabled()",
      "Menu 95 Ext": "",
      "Menu 95 Main Bind": "this.commandSave.bind(this)",
      "Menu 95 Actor Bind": "",
      "---Menu 96---": "",
      "Menu 96 Name": "",
      "Menu 96 Symbol": "",
      "Menu 96 Show": "",
      "Menu 96 Enabled": "",
      "Menu 96 Ext": "",
      "Menu 96 Main Bind": "",
      "Menu 96 Actor Bind": "",
      "---Menu 97---": "",
      "Menu 97 Name": "",
      "Menu 97 Symbol": "",
      "Menu 97 Show": "",
      "Menu 97 Enabled": "",
      "Menu 97 Ext": "",
      "Menu 97 Main Bind": "",
      "Menu 97 Actor Bind": "",
      "---Menu 98---": "",
      "Menu 98 Name": "",
      "Menu 98 Symbol": "",
      "Menu 98 Show": "",
      "Menu 98 Enabled": "",
      "Menu 98 Ext": "",
      "Menu 98 Main Bind": "",
      "Menu 98 Actor Bind": "",
      "---Menu 99---": "",
      "Menu 99 Name": "'Debug'",
      "Menu 99 Symbol": "debug",
      "Menu 99 Show": "false",
      "Menu 99 Enabled": "true",
      "Menu 99 Ext": "",
      "Menu 99 Main Bind": "this.commandDebug.bind(this)",
      "Menu 99 Actor Bind": "",
      "---Menu 100---": "",
      "Menu 100 Name": "TextManager.gameEnd",
      "Menu 100 Symbol": "gameEnd",
      "Menu 100 Show": "true",
      "Menu 100 Enabled": "this.isGameEndEnabled()",
      "Menu 100 Ext": "",
      "Menu 100 Main Bind": "this.commandGameEnd.bind(this)",
      "Menu 100 Actor Bind": ""
    }
  },
  {
    "name": "Community_Basic",
    "status": true,
    "description": "基本的なパラメーターを設定するプラグインです。",
    "parameters": {
      "cacheLimit": "20",
      "screenWidth": "1024",
      "screenHeight": "576",
      "changeWindowWidthTo": "924",
      "changeWindowHeightTo": "",
      "renderingMode": "auto",
      "alwaysDash": "off"
    }
  },
  {
    "name": "TRP_SkitConfig",
    "status": true,
    "description": "TRP_Skitの設定用プラグイン。TRP_Skitより上に配置。",
    "parameters": {
      "categoryBasic": "==============================",
      "SkitActorSettings": "[\"{\\\"name\\\":\\\"pic\\\",\\\"inputName\\\":\\\"pic\\\",\\\"fileName\\\":\\\"pic\\\",\\\"displayOffsetY\\\":\\\"0\\\",\\\"animationOffsetX\\\":\\\"0\\\",\\\"animationOffsetY\\\":\\\"0\\\"}\",\"{\\\"name\\\":\\\"text\\\",\\\"inputName\\\":\\\"\\\",\\\"fileName\\\":\\\"text\\\",\\\"displayOffsetY\\\":\\\"0\\\",\\\"animationOffsetX\\\":\\\"0\\\",\\\"animationOffsetY\\\":\\\"0\\\"}\",\"{\\\"name\\\":\\\"夏尔\\\",\\\"inputName\\\":\\\"\\\",\\\"fileName\\\":\\\"ciel\\\",\\\"displayOffsetY\\\":\\\"0\\\",\\\"animationOffsetX\\\":\\\"0\\\",\\\"animationOffsetY\\\":\\\"0\\\"}\",\"{\\\"name\\\":\\\"诺埃尔\\\",\\\"inputName\\\":\\\"\\\",\\\"fileName\\\":\\\"noel\\\",\\\"displayOffsetY\\\":\\\"0\\\",\\\"animationOffsetX\\\":\\\"0\\\",\\\"animationOffsetY\\\":\\\"0\\\"}\",\"{\\\"name\\\":\\\"维奥\\\",\\\"inputName\\\":\\\"\\\",\\\"fileName\\\":\\\"vaio\\\",\\\"displayOffsetY\\\":\\\"0\\\",\\\"animationOffsetX\\\":\\\"0\\\",\\\"animationOffsetY\\\":\\\"0\\\"}\",\"{\\\"name\\\":\\\"小桃\\\",\\\"inputName\\\":\\\"\\\",\\\"fileName\\\":\\\"momono\\\",\\\"displayOffsetY\\\":\\\"0\\\",\\\"animationOffsetX\\\":\\\"0\\\",\\\"animationOffsetY\\\":\\\"0\\\"}\",\"{\\\"name\\\":\\\"item\\\",\\\"inputName\\\":\\\"\\\",\\\"fileName\\\":\\\"item\\\",\\\"displayOffsetY\\\":\\\"-250\\\",\\\"animationOffsetX\\\":\\\"0\\\",\\\"animationOffsetY\\\":\\\"0\\\"}\",\"{\\\"name\\\":\\\"莉拉\\\",\\\"inputName\\\":\\\"\\\",\\\"fileName\\\":\\\"lila\\\",\\\"displayOffsetY\\\":\\\"0\\\",\\\"animationOffsetX\\\":\\\"0\\\",\\\"animationOffsetY\\\":\\\"0\\\"}\",\"{\\\"name\\\":\\\"拉姆\\\",\\\"inputName\\\":\\\"\\\",\\\"fileName\\\":\\\"ram\\\",\\\"displayOffsetY\\\":\\\"0\\\",\\\"animationOffsetX\\\":\\\"0\\\",\\\"animationOffsetY\\\":\\\"0\\\"}\"]",
      "firstPictureId": "1",
      "lastPictureId": "70",
      "useDefaultExpression": "false",
      "categoryDisplayPosition": "────────────────",
      "zOrder": "1",
      "verticalPositionType": "1",
      "baseOffsetY": "0",
      "xPosition": "[\"{\\\"name\\\":\\\"中央\\\",\\\"position\\\":\\\"5.0\\\"}\",\"{\\\"name\\\":\\\"center\\\",\\\"position\\\":\\\"5.0\\\"}\",\"{\\\"name\\\":\\\"左\\\",\\\"position\\\":\\\"2.0\\\"}\",\"{\\\"name\\\":\\\"left\\\",\\\"position\\\":\\\"1.6\\\"}\",\"{\\\"name\\\":\\\"右\\\",\\\"position\\\":\\\"7.0\\\"}\",\"{\\\"name\\\":\\\"right\\\",\\\"position\\\":\\\"8.2\\\"}\",\"{\\\"name\\\":\\\"left2\\\",\\\"position\\\":\\\"4.0\\\"}\",\"{\\\"name\\\":\\\"right2\\\",\\\"position\\\":\\\"6.4\\\"}\",\"{\\\"name\\\":\\\"left3\\\",\\\"position\\\":\\\"2.8\\\"}\",\"{\\\"name\\\":\\\"center2\\\",\\\"position\\\":\\\"5.6\\\"}\"]",
      "noReverse": "true",
      "noAnimationMirror": "",
      "useRightDirection": "false",
      "bustsScale": "100",
      "border": "================================",
      "macro": "[\"{\\\"name\\\":\\\"pop1\\\",\\\"macro\\\":\\\"jump shizu t 30 d 180\\\"}\",\"{\\\"name\\\":\\\"pop2\\\",\\\"macro\\\":\\\"jump shizu t 80\\\"}\",\"{\\\"name\\\":\\\"pop\\\",\\\"macro\\\":\\\"sequence shizu t d pop1 pop2\\\"}\",\"{\\\"name\\\":\\\"double1\\\",\\\"macro\\\":\\\"jump shizu t 30 1.7\\\"}\",\"{\\\"name\\\":\\\"double\\\",\\\"macro\\\":\\\"sequence shizu t d double1 double1\\\"}\",\"{\\\"name\\\":\\\"nod\\\",\\\"macro\\\":\\\"jump shizu t 25 0.9 180\\\"}\",\"{\\\"name\\\":\\\"stamp1\\\",\\\"macro\\\":\\\"jump shizu t 5 0.3\\\"}\",\"{\\\"name\\\":\\\"stamp\\\",\\\"macro\\\":\\\"sequence shizu t t stamp1 stamp1 stamp1 stamp1 stamp1 stamp1\\\"}\",\"{\\\"name\\\":\\\"slide\\\",\\\"macro\\\":\\\"slidef shizu t\\\"}\",\"{\\\"name\\\":\\\"slidef\\\",\\\"macro\\\":\\\"shake shizu t 10 1 15 t\\\"}\",\"{\\\"name\\\":\\\"slideb\\\",\\\"macro\\\":\\\"shake shizu t 10 1 15\\\"}\",\"{\\\"name\\\":\\\"tremble\\\",\\\"macro\\\":\\\"shake shizu t 4 10 6\\\"}\",\"{\\\"name\\\":\\\"rock\\\",\\\"macro\\\":\\\"shake shizu t 5 5 25 t\\\"}\",\"{\\\"name\\\":\\\"push\\\",\\\"macro\\\":\\\"shake shizu t 17 1 16 t\\\"}\",\"{\\\"name\\\":\\\"attack\\\",\\\"macro\\\":\\\"shake shizu t 17 1 15\\\"}\"]",
      "macro2": "[]",
      "macro3": "[]",
      "macro4": "[]",
      "macro5": "[\"{\\\"name\\\":\\\"loopstamp1\\\",\\\"macro\\\":\\\"jump shizu t 5 0.3\\\"}\",\"{\\\"name\\\":\\\"loopstamp\\\",\\\"macro\\\":\\\"loop shizu t d stamp1\\\"}\",\"{\\\"name\\\":\\\"looptremble1\\\",\\\"macro\\\":\\\"shake shizu t 4 10 2\\\"}\",\"{\\\"name\\\":\\\"looptremble\\\",\\\"macro\\\":\\\"loop shizu t d looptremble1\\\"}\",\"{\\\"name\\\":\\\"looprock1\\\",\\\"macro\\\":\\\"shake shizu t 5 4 25 t\\\"}\",\"{\\\"name\\\":\\\"looprock\\\",\\\"macro\\\":\\\"loop shizu t d looprock1\\\"}\",\"{\\\"name\\\":\\\"loopfloat1\\\",\\\"macro\\\":\\\"y shizu t 10 45\\\"}\",\"{\\\"name\\\":\\\"loopfloat2\\\",\\\"macro\\\":\\\"y shizu t -10 45\\\"}\",\"{\\\"name\\\":\\\"loopfloat\\\",\\\"macro\\\":\\\"loop shizu t d loopfloat1 loopfloat2\\\"}\"]",
      "mobNames": "[]",
      "controlCharacters": "{\"expression\":\"SE\",\"pose\":\"SP\",\"motion\":\"SM\",\"animation\":\"SA\"}",
      "categoryAppearCommands": "────────────────",
      "defaultPositionX": "左",
      "pushInMargin": "1.5",
      "pushInSpeed": "10",
      "fadeIn": "{\"duration\":\"12\",\"wait\":\"false\",\"easeType\":\"6\",\"pushIn\":\"false\"}",
      "slideIn": "{\"speed\":\"17\",\"slideLength\":\"2\",\"wait\":\"false\",\"easeType\":\"3\",\"pushIn\":\"true\"}",
      "moveIn": "{\"speed\":\"14\",\"wait\":\"true\",\"easeType\":\"3\",\"pushIn\":\"true\"}",
      "categoryDisappearCommands": "────────────────",
      "defaultDisappear": "2",
      "fadeOut": "{\"duration\":\"12\",\"wait\":\"true\",\"easeType\":\"3\"}",
      "slideOut": "{\"speed\":\"9\",\"slideLength\":\"1\",\"wait\":\"false\",\"easeType\":\"3\"}",
      "moveOut": "{\"speed\":\"14\",\"wait\":\"true\",\"easeType\":\"3\"}",
      "categoryExpCommands": "────────────────",
      "expression": "{\"duration\":\"90\",\"wait\":\"false\"}",
      "pose": "{\"style\":\"0\",\"duration\":\"0\",\"wait\":\"false\",\"easeType\":\"0\"}",
      "categoryMoveCommands": "────────────────",
      "speed": "[\"{\\\"name\\\":\\\"verySlow\\\",\\\"speed\\\":\\\"3.0\\\"}\",\"{\\\"name\\\":\\\"slow\\\",\\\"speed\\\":\\\"6.0\\\"}\",\"{\\\"name\\\":\\\"littleSlow\\\",\\\"speed\\\":\\\"9.0\\\"}\",\"{\\\"name\\\":\\\"normal\\\",\\\"speed\\\":\\\"12.0\\\"}\",\"{\\\"name\\\":\\\"littleFast\\\",\\\"speed\\\":\\\"15.0\\\"}\",\"{\\\"name\\\":\\\"fast\\\",\\\"speed\\\":\\\"20.0\\\"}\",\"{\\\"name\\\":\\\"veryFast\\\",\\\"speed\\\":\\\"30.0\\\"}\"]",
      "move": "{\"speed\":\"12\",\"wait\":\"false\",\"easeType\":\"0\"}",
      "yMove": "{\"duration\":\"20\",\"wait\":\"false\",\"easeType\":\"3\"}",
      "jump": "{\"height\":\"80\",\"gravity\":\"1.5\",\"wait\":\"false\"}",
      "step": "{\"height\":\"20\",\"gravity\":\"0.5\",\"speed\":\"1.5\",\"wait\":\"false\",\"relative\":\"0\",\"easeType\":\"3\"}",
      "flip": "{\"num\":\"1\",\"durationPerCount\":\"14\",\"wait\":\"true\",\"easeType\":\"0\"}",
      "shake": "{\"strength\":\"8\",\"count\":\"2\",\"durationPerCount\":\"6\",\"wait\":\"false\",\"easeType\":\"3\"}",
      "angle": "{\"angle\":\"360\",\"duration\":\"60\",\"relative\":\"1\",\"wait\":\"false\",\"easeType\":\"3\"}",
      "scale": "{\"scaleX\":\"100\",\"scaleY\":\"100\",\"duration\":\"20\",\"relative\":\"0\",\"wait\":\"false\",\"easeType\":\"3\"}",
      "categoryEffectCommands": "────────────────",
      "animation": "{\"list\":\"[]\",\"focus\":\"true\",\"mirror\":\"false\",\"wait\":\"false\"}",
      "opacity": "{\"duration\":\"20\",\"opacity\":\"0\",\"relative\":\"0\",\"wait\":\"false\",\"easeType\":\"3\"}",
      "focus": "{\"duration\":\"10\",\"wait\":\"false\",\"easeType\":\"3\"}",
      "unFocus": "{\"duration\":\"1\",\"tone\":\"0 0 0 0\",\"scale\":\"100.0\",\"wait\":\"false\",\"easeType\":\"3\"}",
      "emphasize": "{\"duration\":\"20\",\"tone\":\"0 0 0 0\",\"scaleX\":\"120\",\"scaleY\":\"120\",\"num\":\"1\",\"interval\":\"20\",\"wait\":\"true\",\"easeType\":\"3\"}",
      "tint": "{\"duration\":\"1\",\"tone\":\"-30 -30 -30 30\",\"wait\":\"false\"}"
    }
  },
  {
    "name": "TRP_Skit",
    "status": true,
    "description": "立ち絵操作プラグイン。",
    "parameters": {}
  },
  {
    "name": "TRP_SkitExAutoShow",
    "status": true,
    "description": "TRP_Skitに立ち絵の自動表示/非表示機能を追加",
    "parameters": {
      "showCommand": "slideIn",
      "hideCommand": "slideOut",
      "positions": "[\"left\"]"
    }
  },
  {
    "name": "TRP_ParticlePreset",
    "status": true,
    "description": "",
    "parameters": {}
  },
  {
    "name": "TRP_Particle",
    "status": true,
    "description": "※TRP_Particle_Presetより下に配置",
    "parameters": {
      "importLibrary": "true",
      "importFilter": "true",
      "systemParticles": "[\"particle set click click\"]",
      "commandName": "particle,パーティクル",
      "keepPictureOrder": "false",
      "walkOffset": "16",
      "dashOffset": "16",
      "categoryClear": "==============================",
      "clearCharacterOnMapChange": "true",
      "clearPartyOnMapChange": "true",
      "clearScreenOnMapChange": "true",
      "clearBattleScreenOnEnd": "false",
      "clearBattleCharaOnEnd": "true",
      "categoryPerformance": "==============================",
      "regionMargin": "2",
      "outsideMargin": "6",
      "maxParticles": "100000",
      "useCache": "false",
      "categoryConflict": "==============================",
      "disableState": "false",
      "disableSkill": "false",
      "disableRoute": "false",
      "cacheBeforeTerminate": "false",
      "categorySenior": "==============================",
      "sceneTypes": "[\"Scene_Menu-Scene_Save-Scene_Item-Scene_Equip-Scene_Actor-Scene_Skill-Scene_Status\",\"Scene_Title\",\"Scene_Load\",\"Scene_Options\",\"Scene_Shop\",\"Scene_Gameover\"]",
      "noRewriteFunctions": "false",
      "categoryDebug": "==============================",
      "displayCount": "false",
      "errorLog": "true",
      "windowBugFix": "true"
    }
  },
  {
    "name": "TRP_ParticleEditor",
    "status": true,
    "description": "※TRP_Particleより下に配置",
    "parameters": {
      "showGuide": "true",
      "paramFontSize": "18",
      "noColorCode": "false",
      "buttonFontSize": "13",
      "buttonWidth": "86",
      "saveAsArray": "false",
      "copyAsArray": "true"
    }
  },
  {
    "name": "Window",
    "status": true,
    "description": "",
    "parameters": {}
  },
  {
    "name": "GraphicsRenderFix",
    "status": true,
    "description": "放置していると画面がフリーズするのを修正",
    "parameters": {}
  },
  {
    "name": "Exhydra_OptionsMenu_ExtraOptions",
    "status": true,
    "description": "[1.05] Additional options for the options menu.",
    "parameters": {
      "─ Title Screen": "───────────────",
      "Remove from Title Screen": "false",
      "─ Game Menu": "───────────────",
      "Remove from Game Menu": "false",
      "─ Options Menu": "───────────────",
      "Remove Always Dash": "false",
      "Remove Command Remember": "true",
      "Remove BGM Volume": "false",
      "Remove BGS Volume": "true",
      "Remove ME Volume": "true",
      "Remove SE Volume": "false",
      "─ Custom Options": "───────────────",
      "Option 1 Label": "",
      "Option 1 Type": "",
      "Option 1 ID": "",
      "Option 1 Default": "",
      "Option 1 MinMax": "",
      "Option 1 Hide": "",
      "Option 2 Label": "",
      "Option 2 Type": "",
      "Option 2 ID": "",
      "Option 2 Default": "",
      "Option 2 MinMax": "",
      "Option 2 Hide": "",
      "Option 3 Label": "",
      "Option 3 Type": "",
      "Option 3 ID": "",
      "Option 3 Default": "",
      "Option 3 MinMax": "",
      "Option 3 Hide": "",
      "Option 4 Label": "",
      "Option 4 Type": "",
      "Option 4 ID": "",
      "Option 4 Default": "",
      "Option 4 Hide": "",
      "Option 4 MinMax": "",
      "Option 5 Label": "",
      "Option 5 Type": "",
      "Option 5 ID": "",
      "Option 5 Default": "",
      "Option 5 MinMax": "",
      "Option 5 Hide": "",
      "─ Plugin": "───────────────",
      "Plugin GID": "eXa-JEuInwXq4chcgu9"
    }
  },
  {
    "name": "FTKR_ItemCategoryFixed",
    "status": true,
    "description": "v1.0.3 アイテムボックスのカテゴリ選択を無くす",
    "parameters": {
      "Item Category": "item"
    }
  },
  {
    "name": "AudioStreaming",
    "status": true,
    "description": "音声読み込みを高速化し、oggファイルのみを使用します。",
    "parameters": {
      "mode": "10",
      "deleteM4a": "false"
    }
  },
  {
    "name": "ParallaxLayerMap",
    "status": true,
    "description": "多層レイヤー一枚絵マッププラグイン",
    "parameters": {}
  },
  {
    "name": "TMRegionPassable",
    "status": true,
    "description": "その場所が通行可能かどうかをリージョンで設定できるようになります。",
    "parameters": {
      "passableRegions": "251",
      "dontPassRegions": "252 253",
      "counterRegions": "253"
    }
  },
  {
    "name": "MPP_ChoiceEX",
    "status": true,
    "description": "【ver.3.11】選択肢の機能拡張",
    "parameters": {
      "maxPageRow": "10",
      "Disabled Index": "none",
      "=== Command ===": "",
      "Plugin Commands": "{\"ChoicePos\":\"ChoicePos\",\"ChoiceVariableId\":\"ChoiceVariableId\",\"ChoiceRect\":\"ChoiceRect\",\"ChoiceUnderMessage\":\"ChoiceUnderMessage\"}",
      "Event Comment": "{\"ChoiceHelp\":\"選択肢ヘルプ\"}"
    }
  },
  {
    "name": "FilterController",
    "status": true,
    "description": "FilterController",
    "parameters": {
      "変数に小数点が使えるようにする": "true",
      "displacementImage": "DisplacementMap",
      "enabledAll-Settings": "",
      "enabledAll-ShowInOptionMenu": "true",
      "enabledAll-Text": "画面特效",
      "enabledAll-DefaultValue": "true"
    }
  },
  {
    "name": "FilterController2",
    "status": true,
    "description": "",
    "parameters": {}
  },
  {
    "name": "StatusBustImage",
    "status": true,
    "description": "バストアップ表示プラグイン",
    "parameters": {
      "画像X座標": "0",
      "画像Y座標": "0",
      "装備_画像X座標": "",
      "装備_画像Y座標": "",
      "スキル_画像X座標": "",
      "スキル_画像Y座標": "",
      "メイン_画像X座標": "530",
      "メイン_画像Y座標": "270",
      "表示優先度": "1",
      "ベース画像原点": "1",
      "追加画像原点": "2"
    }
  },
  {
    "name": "kz_MenuStatus",
    "status": true,
    "description": "メニューステータスの自由設置",
    "parameters": {
      "Status Rows": "1",
      "Status Cols": "1",
      "Status Window X": "1",
      "Status Window Y": "1",
      "Status Window Width": "1",
      "Status Window Height": "1",
      "Status Window Padding": "0",
      "State X": "0",
      "State Y": "0",
      "State Width": "-1",
      "Actor Icon X": "-1",
      "Actor Icon Y": "-1",
      "Background PNG": "",
      "Display Text": "[\"'現在の目的',35,490,190,24,15,0\",\"$gameVariables.value(2),240,490,150,24,15,0\"]",
      "Display Picture": "[]",
      "Display Gauge": "[]"
    }
  },
  {
    "name": "kz_PicMenu",
    "status": true,
    "description": "メニューコマンドの画像化",
    "parameters": {
      "icon width": "100",
      "icon height": "100",
      "item icon": "0",
      "skill icon": "1",
      "equip icon": "2",
      "status icon": "3",
      "formation icon": "4",
      "options icon": "5",
      "save icon": "6",
      "gameEnd icon": "7",
      "icon itemrect": "50",
      "icon rows": "1",
      "icon cols": "4",
      "icon maxexpansion": "0.00",
      "x overhead": "277",
      "y overhead": "0",
      "commandwindow x": "800",
      "commandwindow y": "25",
      "commandwindow width": "800",
      "commandwindow height": "200",
      "display cursor": "true",
      "window background file": "menuback"
    }
  },
  {
    "name": "MOG_TitlePictureCom",
    "status": true,
    "description": "(v1.6 *) Adiciona comandos em imagens no lugar da janela.",
    "parameters": {
      "-> Main <<<<<<<<<<<<<<<<<<<<<<<": "",
      "Animation Mode": "0",
      "Left & Right Input": "true",
      "Com Fade-In Duration": "7",
      "Slide X-Axis": "-100",
      "Slide Y-Axis": "0",
      "": "",
      "-> Smart Background  <<<<<<<<<<<<<<<<<<<<<<<": "",
      "Smart Background": "true",
      "Background X-Axis": "0",
      "Background Y-Axis": "0",
      "Background Fade-In Duration": "90",
      "-> Title Sprite <<<<<<<<<<<<<<<<<<<<<<<": "",
      "Title Sprite": "true",
      "Title Sprite X-Axis": "512",
      "Title Sprite Y-Axis": "280",
      "Fade-In Duration": "40",
      "Zoom Effect": "false",
      "Zoom Speed": "40",
      "-> Cursor <<<<<<<<<<<<<<<<<<<<<<<": "",
      "Cursor X-Axis": "20",
      "Cursor Y-Axis": "0",
      "Cursor Visible": "true",
      "Cursor Wave Animation": "true",
      "Cursor Rotation Animation": "false",
      "Cursor Rotation Speed": "0.07",
      "-> Commands <<<<<<<<<<<<<<<<<<<<<<<": "",
      "Command Pos 1": "100,500",
      "Command Pos 2": "330,500",
      "Command Pos 3": "570,500",
      "Command Pos 4": "750,500",
      "Command Pos 5": "345,498",
      "Command Pos 6": "345,530",
      "Command Pos 7": "0,192",
      "Command Pos 8": "0,224",
      "Command Pos 9": "0,256",
      "Command Pos 10": "0,288"
    }
  },
  {
    "name": "BB_CustomSaveWindow",
    "status": true,
    "description": "セーブウインドウ改造プラグイン",
    "parameters": {
      "OutsideFrameColor": "0",
      "OutsideFrameOpacity": "0",
      "InsideFrameColor": "0",
      "InsideFrameOpacity": "0",
      "MaxItem": "4",
      "Item0": "7",
      "Item0Length": "300",
      "Item1title": "プレイ時間",
      "Item1": "2",
      "Item2title": "",
      "Item2": "3",
      "Item3title": "",
      "Item3": "0",
      "Item4title": "",
      "Item4": "0",
      "Item5": "0",
      "ItemValue1": "3",
      "ItemValue2": "1",
      "ItemValue3": "3",
      "ItemValue4": "4",
      "ItemValue1unit": "",
      "ItemValue2unit": "",
      "ItemValue3unit": "",
      "ItemValue4unit": "",
      "TitleFramelength1": "110",
      "TitleFramelength2": "110",
      "TitleFramelength3": "110",
      "TitleFramelength4": "110",
      "CharacterPositionY": "6",
      "CharacterOpacity": "2",
      "LevelPositionY": "23",
      "LevelOnOff": "0"
    }
  },
  {
    "name": "MessageSkip",
    "status": true,
    "description": "メッセージスキッププラグイン",
    "parameters": {
      "スキップキー": "shift",
      "オートキー": "control",
      "スキップスイッチ": "0",
      "オートスイッチ": "0",
      "スキップアイコン": "140",
      "オートアイコン": "75",
      "アイコンX": "0",
      "アイコンY": "0",
      "押し続けスキップ": "true",
      "オート待機フレーム": "textSize * 2.5+30",
      "終了解除スイッチID": "0",
      "スキップピクチャ": "",
      "ボタン原点": "0",
      "ボタン表示スイッチID": "0",
      "スキップピクチャX": "910",
      "スキップピクチャY": "20",
      "オートピクチャ": "",
      "オートピクチャX": "850",
      "オートピクチャY": "20",
      "無効化スイッチ": "429"
    }
  },
  {
    "name": "UTA_CommonSave",
    "status": true,
    "description": "共有のセーブデータを作成し、指定したスイッチ・変数の状態をセーブデータ間で共有します。",
    "parameters": {
      "Target Switches": "1,102-104,106,107,111,112,421-426",
      "Target Variables": "",
      "Is Auto": "true",
      "Auto on Gameover": "false",
      "Show Trace": "false"
    }
  },
  {
    "name": "Vitsuno_CommonSave",
    "status": true,
    "description": "ファイル共有のセーブデータシステムを構築します。",
    "parameters": {
      "Savefile ID": "-2"
    }
  },
  {
    "name": "Vitsuno_PictureGallery",
    "status": true,
    "description": "ピクチャーギャラリー機能を加えるプラグインです。",
    "parameters": {
      "On Menu": "0",
      "Command Name": "ギャラリー",
      "Max Size": "65",
      "Thumbnail Width": "213",
      "Thumbnail Height": "120",
      "None File": "GalleryNone",
      "Use Common Mode": "1",
      "diffImageList": "[\"{\\\"baseImage\\\":\\\"001\\\",\\\"diffImages\\\":\\\"[\\\\\\\"001a\\\\\\\"]\\\"}\",\"{\\\"baseImage\\\":\\\"004\\\",\\\"diffImages\\\":\\\"[\\\\\\\"004a\\\\\\\"]\\\"}\",\"{\\\"baseImage\\\":\\\"005\\\",\\\"diffImages\\\":\\\"[\\\\\\\"005a\\\\\\\",\\\\\\\"005b\\\\\\\"]\\\"}\",\"{\\\"baseImage\\\":\\\"006\\\",\\\"diffImages\\\":\\\"[\\\\\\\"006a\\\\\\\"]\\\"}\",\"{\\\"baseImage\\\":\\\"009\\\",\\\"diffImages\\\":\\\"[\\\\\\\"009b\\\\\\\",\\\\\\\"009a\\\\\\\"]\\\"}\",\"{\\\"baseImage\\\":\\\"010\\\",\\\"diffImages\\\":\\\"[\\\\\\\"010a\\\\\\\"]\\\"}\",\"{\\\"baseImage\\\":\\\"011\\\",\\\"diffImages\\\":\\\"[\\\\\\\"011a\\\\\\\"]\\\"}\",\"{\\\"baseImage\\\":\\\"013\\\",\\\"diffImages\\\":\\\"[\\\\\\\"013a\\\\\\\"]\\\"}\",\"{\\\"baseImage\\\":\\\"014\\\",\\\"diffImages\\\":\\\"[\\\\\\\"014a\\\\\\\"]\\\"}\",\"{\\\"baseImage\\\":\\\"015\\\",\\\"diffImages\\\":\\\"[\\\\\\\"015a\\\\\\\",\\\\\\\"015b\\\\\\\"]\\\"}\",\"{\\\"baseImage\\\":\\\"016\\\",\\\"diffImages\\\":\\\"[\\\\\\\"016a\\\\\\\",\\\\\\\"016b\\\\\\\"]\\\"}\",\"{\\\"baseImage\\\":\\\"017\\\",\\\"diffImages\\\":\\\"[\\\\\\\"017a\\\\\\\"]\\\"}\",\"{\\\"baseImage\\\":\\\"018\\\",\\\"diffImages\\\":\\\"[\\\\\\\"018a\\\\\\\"]\\\"}\",\"{\\\"baseImage\\\":\\\"019\\\",\\\"diffImages\\\":\\\"[\\\\\\\"019a\\\\\\\"]\\\"}\",\"{\\\"baseImage\\\":\\\"024\\\",\\\"diffImages\\\":\\\"[\\\\\\\"024a\\\\\\\"]\\\"}\",\"{\\\"baseImage\\\":\\\"025\\\",\\\"diffImages\\\":\\\"[\\\\\\\"025b\\\\\\\",\\\\\\\"025a\\\\\\\"]\\\"}\",\"{\\\"baseImage\\\":\\\"027\\\",\\\"diffImages\\\":\\\"[\\\\\\\"027a\\\\\\\",\\\\\\\"027b\\\\\\\"]\\\"}\",\"{\\\"baseImage\\\":\\\"028\\\",\\\"diffImages\\\":\\\"[\\\\\\\"028a\\\\\\\",\\\\\\\"028b\\\\\\\"]\\\"}\",\"{\\\"baseImage\\\":\\\"029\\\",\\\"diffImages\\\":\\\"[\\\\\\\"029a\\\\\\\"]\\\"}\",\"{\\\"baseImage\\\":\\\"030\\\",\\\"diffImages\\\":\\\"[\\\\\\\"030a\\\\\\\"]\\\"}\",\"{\\\"baseImage\\\":\\\"032\\\",\\\"diffImages\\\":\\\"[\\\\\\\"032a\\\\\\\",\\\\\\\"032b\\\\\\\"]\\\"}\",\"{\\\"baseImage\\\":\\\"035\\\",\\\"diffImages\\\":\\\"[\\\\\\\"035a\\\\\\\"]\\\"}\",\"{\\\"baseImage\\\":\\\"036\\\",\\\"diffImages\\\":\\\"[\\\\\\\"036a\\\\\\\",\\\\\\\"036b\\\\\\\"]\\\"}\",\"{\\\"baseImage\\\":\\\"044\\\",\\\"diffImages\\\":\\\"[\\\\\\\"044a\\\\\\\",\\\\\\\"044b\\\\\\\",\\\\\\\"044c\\\\\\\"]\\\"}\",\"{\\\"baseImage\\\":\\\"045\\\",\\\"diffImages\\\":\\\"[\\\\\\\"045a\\\\\\\"]\\\"}\",\"{\\\"baseImage\\\":\\\"046\\\",\\\"diffImages\\\":\\\"[\\\\\\\"046a\\\\\\\"]\\\"}\",\"{\\\"baseImage\\\":\\\"047\\\",\\\"diffImages\\\":\\\"[\\\\\\\"047a\\\\\\\"]\\\"}\",\"{\\\"baseImage\\\":\\\"048\\\",\\\"diffImages\\\":\\\"[\\\\\\\"048a\\\\\\\",\\\\\\\"048b\\\\\\\",\\\\\\\"048c\\\\\\\"]\\\"}\",\"{\\\"baseImage\\\":\\\"049\\\",\\\"diffImages\\\":\\\"[\\\\\\\"049a\\\\\\\"]\\\"}\",\"{\\\"baseImage\\\":\\\"053\\\",\\\"diffImages\\\":\\\"[\\\\\\\"053a\\\\\\\"]\\\"}\",\"{\\\"baseImage\\\":\\\"054\\\",\\\"diffImages\\\":\\\"[\\\\\\\"054a\\\\\\\"]\\\"}\",\"{\\\"baseImage\\\":\\\"062\\\",\\\"diffImages\\\":\\\"[\\\\\\\"062a\\\\\\\"]\\\"}\",\"{\\\"baseImage\\\":\\\"115\\\",\\\"diffImages\\\":\\\"[\\\\\\\"115a\\\\\\\",\\\\\\\"115b\\\\\\\"]\\\"}\",\"{\\\"baseImage\\\":\\\"119\\\",\\\"diffImages\\\":\\\"[\\\\\\\"119a\\\\\\\"]\\\"}\",\"{\\\"baseImage\\\":\\\"148\\\",\\\"diffImages\\\":\\\"[\\\\\\\"148a\\\\\\\"]\\\"}\",\"{\\\"baseImage\\\":\\\"144\\\",\\\"diffImages\\\":\\\"[\\\\\\\"144a\\\\\\\"]\\\"}\",\"{\\\"baseImage\\\":\\\"008\\\",\\\"diffImages\\\":\\\"[\\\\\\\"008a\\\\\\\"]\\\"}\",\"{\\\"baseImage\\\":\\\"031\\\",\\\"diffImages\\\":\\\"[\\\\\\\"031a\\\\\\\",\\\\\\\"031b\\\\\\\"]\\\"}\",\"{\\\"baseImage\\\":\\\"064\\\",\\\"diffImages\\\":\\\"[\\\\\\\"064a\\\\\\\",\\\\\\\"064b\\\\\\\"]\\\"}\",\"{\\\"baseImage\\\":\\\"065\\\",\\\"diffImages\\\":\\\"[\\\\\\\"065a\\\\\\\"]\\\"}\",\"{\\\"baseImage\\\":\\\"069\\\",\\\"diffImages\\\":\\\"[\\\\\\\"069a\\\\\\\"]\\\"}\",\"{\\\"baseImage\\\":\\\"071\\\",\\\"diffImages\\\":\\\"[\\\\\\\"071a\\\\\\\",\\\\\\\"071b\\\\\\\"]\\\"}\"]"
    }
  },
  {
    "name": "OrangeMapshot",
    "status": false,
    "description": "This plugin will save a picture of the entire map on a Mapshots folder when you press a key. <OrangeMapshot>",
    "parameters": {
      "useMapName": "true",
      "layerType": "0",
      "drawAutoShadows": "false",
      "drawEvents": "true",
      "keyCode": "44",
      "imageType": "png",
      "imageQuality": "70",
      "imagePath": "C:\\Users\\PC_User\\Documents"
    }
  },
  {
    "name": "Text2Frame",
    "status": true,
    "description": "テキストファイル(.txtファイルなど)から「文章の表示」イベントコマンドに簡単に変換するための、開発支援プラグインです。",
    "parameters": {
      "Default Window Position": "下",
      "Default Background": "ウインドウ",
      "Default Scenario Folder": "text",
      "Default Scenario File": "message.txt",
      "Default Common Event ID": "1",
      "Default MapID": "3",
      "Default EventID": "12",
      "IsOverwrite": "false",
      "Comment Out Char": "%",
      "IsDebug": "false"
    }
  },
  {
    "name": "GradientWipe",
    "status": true,
    "description": "トランジション効果",
    "parameters": {
      "-- 画面トランジション --": "",
      "画面フェードに適用": "true",
      "画面フェード用画像": "01",
      "画面フェードイン用画像": "",
      "画面フェードアウト用画像": "",
      "画面フェードの柔らかさ": "15",
      "画面フェード時間": "24",
      "-- メッセージウィンドウ --": "",
      "メッセージウィンドウに適用": "false",
      "メッセージフェード用画像": "",
      "メッセージフェード時間": "24"
    }
  },
  {
    "name": "UnfollowTouchTracks",
    "status": true,
    "description": "タッチ後の目的地を表す軌跡を非表示にするプラグインです。",
    "parameters": {
      "----基本的な設定----": "",
      "スイッチ番号": "460"
    }
  },
  {
    "name": "AnotherNewGame",
    "status": true,
    "description": "アナザーニューゲーム追加プラグイン",
    "parameters": {
      "anotherDataList": "[\"{\\\"name\\\":\\\"ギャラリー\\\",\\\"mapId\\\":\\\"20\\\",\\\"mapX\\\":\\\"1\\\",\\\"mapY\\\":\\\"1\\\",\\\"hidden\\\":\\\"false\\\",\\\"disable\\\":\\\"false\\\",\\\"addPosition\\\":\\\"3\\\",\\\"switchId\\\":\\\"0\\\",\\\"fileLoad\\\":\\\"false\\\",\\\"noFadeout\\\":\\\"false\\\"}\"]",
      "manageNumber": ""
    }
  },
  {
    "name": "MakeScreenCapture",
    "status": true,
    "description": "画面キャプチャ管理プラグイン",
    "parameters": {
      "PNGキャプチャキー": "F6",
      "JPEGキャプチャキー": "none",
      "WEBPキャプチャキー": "none",
      "Ctrl同時押し": "false",
      "Alt同時押し": "false",
      "ファイル名": "",
      "出力場所": "C:\\Users\\PC_User\\OneDrive\\gameshot",
      "保存形式": "png",
      "連番桁数": "2",
      "タイムスタンプ": "true",
      "署名": "",
      "署名サイズ": "22",
      "署名画像": "",
      "実行間隔": "0",
      "効果音": "",
      "JPEG品質": "9"
    }
  },
  {
    "name": "MPP_MapLight",
    "status": true,
    "description": "マップの明るさを設定できるようにします。",
    "parameters": {
      "Light Colors": "[\"255,255,255\",\"200,0,0\",\"100,100,180\",\"0,0,0\",\"170,170,200\"]",
      "Front Light": "{\"Radius\":\"5\",\"Angle\":\"90\",\"Oy\":\"4\",\"Turn Duration\":\"24\"}",
      "Darkness Size": "3",
      "Additive Alpha": "0"
    }
  },
  {
    "name": "MPP_MapLight_Op1",
    "status": true,
    "description": "特定のアイテムを所持しているか、装備することでプレイヤーに灯りが表示されるようになります。",
    "parameters": {}
  },
  {
    "name": "InputTableSelect",
    "status": true,
    "description": "ver1.00 変数の値によって名前入力用の\r\n切り替え可能なテーブルに制限をかけます。",
    "parameters": {
      "select": "10"
    }
  },
  {
    "name": "MessageWindowHidden",
    "status": true,
    "description": "メッセージウィンドウ一時消去プラグイン",
    "parameters": {
      "triggerButton": "[\"control\"]",
      "triggerSwitch": "0",
      "linkPictureNumbers": "[]",
      "linkShowPictureNumbers": "[]",
      "disableLinkSwitchId": "0",
      "disableSwitchId": "0",
      "disableInBattle": "false",
      "disableInChoice": "true",
      "restoreByDecision": "true"
    }
  },
  {
    "name": "LL_GalgeChoiceWindowMV",
    "status": true,
    "description": "ノベルゲーム風選択肢ウィンドウプラグイン",
    "parameters": {
      "imageDeleteGuardList": "[]"
    }
  },
  {
    "name": "KMS_QuickNotification",
    "status": true,
    "description": "[v0.1.1] ポップアップ通知を表示する機能を追加します。",
    "parameters": {
      "Display duration": "300",
      "Display position": "1",
      "Face image size": "12",
      "Font size": "15",
      "Max notification count": "4",
      "Notification SE": "",
      "Notification SE param": "100, 100",
      "Notification skin": "QuickNotificationSkin"
    }
  },
  {
    "name": "Rubi_riru",
    "status": true,
    "description": "ルビ振りを行います。用語登録によるオートルビ振り機能つき。",
    "parameters": {
      "Auto Ruby": "true",
      "Help Auto Ruby": "true",
      "Database Auto Ruby": "true",
      "Jisage": "0",
      "Ruby Size": "-3"
    }
  },
  {
    "name": "Lunatlazur_BackLog",
    "status": true,
    "description": "バックログ表示プラグイン",
    "parameters": {
      "2カラムレイアウト": "false"
    }
  },
  {
    "name": "FPSLimit",
    "status": true,
    "description": "Limits game refresh rate",
    "parameters": {
      "FPS Limit": "60"
    }
  }
];